/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SoundContext = IDL.Variant({
  'bossDefeat' : IDL.Null,
  'worldUnlock' : IDL.Null,
  'bomb' : IDL.Null,
  'clock' : IDL.Null,
  'rewardClaim' : IDL.Null,
  'bossObjective' : IDL.Null,
  'bossVictory' : IDL.Null,
  'layerOpen' : IDL.Null,
  'bossLevelStart' : IDL.Null,
  'tileMatch' : IDL.Null,
  'buttonClick' : IDL.Null,
  'backgroundMusic' : IDL.Null,
  'tileClear' : IDL.Null,
  'tileClick' : IDL.Null,
  'starEarned' : IDL.Null,
  'shuffle' : IDL.Null,
  'magnifier' : IDL.Null,
  'levelComplete' : IDL.Null,
});
export const Theme = IDL.Variant({
  'candyland' : IDL.Null,
  'ocean' : IDL.Null,
  'garden' : IDL.Null,
  'space' : IDL.Null,
  'volcano' : IDL.Null,
  'forest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AudioFile = IDL.Record({
  'id' : IDL.Text,
  'context' : SoundContext,
  'blob' : ExternalBlob,
  'description' : IDL.Text,
  'world' : IDL.Opt(Theme),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAudioFile' : IDL.Func(
      [IDL.Text, SoundContext, IDL.Opt(Theme), ExternalBlob, IDL.Text],
      [],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAudioFile' : IDL.Func([IDL.Text], [], []),
  'getAllAudioFiles' : IDL.Func([], [IDL.Vec(AudioFile)], ['query']),
  'getAudioFile' : IDL.Func([IDL.Text], [AudioFile], ['query']),
  'getAudioFilesByContext' : IDL.Func(
      [SoundContext],
      [IDL.Vec(AudioFile)],
      ['query'],
    ),
  'getAudioFilesByWorld' : IDL.Func([Theme], [IDL.Vec(AudioFile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SoundContext = IDL.Variant({
    'bossDefeat' : IDL.Null,
    'worldUnlock' : IDL.Null,
    'bomb' : IDL.Null,
    'clock' : IDL.Null,
    'rewardClaim' : IDL.Null,
    'bossObjective' : IDL.Null,
    'bossVictory' : IDL.Null,
    'layerOpen' : IDL.Null,
    'bossLevelStart' : IDL.Null,
    'tileMatch' : IDL.Null,
    'buttonClick' : IDL.Null,
    'backgroundMusic' : IDL.Null,
    'tileClear' : IDL.Null,
    'tileClick' : IDL.Null,
    'starEarned' : IDL.Null,
    'shuffle' : IDL.Null,
    'magnifier' : IDL.Null,
    'levelComplete' : IDL.Null,
  });
  const Theme = IDL.Variant({
    'candyland' : IDL.Null,
    'ocean' : IDL.Null,
    'garden' : IDL.Null,
    'space' : IDL.Null,
    'volcano' : IDL.Null,
    'forest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AudioFile = IDL.Record({
    'id' : IDL.Text,
    'context' : SoundContext,
    'blob' : ExternalBlob,
    'description' : IDL.Text,
    'world' : IDL.Opt(Theme),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAudioFile' : IDL.Func(
        [IDL.Text, SoundContext, IDL.Opt(Theme), ExternalBlob, IDL.Text],
        [],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAudioFile' : IDL.Func([IDL.Text], [], []),
    'getAllAudioFiles' : IDL.Func([], [IDL.Vec(AudioFile)], ['query']),
    'getAudioFile' : IDL.Func([IDL.Text], [AudioFile], ['query']),
    'getAudioFilesByContext' : IDL.Func(
        [SoundContext],
        [IDL.Vec(AudioFile)],
        ['query'],
      ),
    'getAudioFilesByWorld' : IDL.Func([Theme], [IDL.Vec(AudioFile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };