/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AudioFile {
  'id' : string,
  'context' : SoundContext,
  'blob' : ExternalBlob,
  'description' : string,
  'world' : [] | [Theme],
}
export type ExternalBlob = Uint8Array;
export type SoundContext = { 'bossDefeat' : null } |
  { 'worldUnlock' : null } |
  { 'bomb' : null } |
  { 'clock' : null } |
  { 'rewardClaim' : null } |
  { 'bossObjective' : null } |
  { 'bossVictory' : null } |
  { 'layerOpen' : null } |
  { 'bossLevelStart' : null } |
  { 'tileMatch' : null } |
  { 'buttonClick' : null } |
  { 'backgroundMusic' : null } |
  { 'tileClear' : null } |
  { 'tileClick' : null } |
  { 'starEarned' : null } |
  { 'shuffle' : null } |
  { 'magnifier' : null } |
  { 'levelComplete' : null };
export type Theme = { 'candyland' : null } |
  { 'ocean' : null } |
  { 'garden' : null } |
  { 'space' : null } |
  { 'volcano' : null } |
  { 'forest' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAudioFile' : ActorMethod<
    [string, SoundContext, [] | [Theme], ExternalBlob, string],
    undefined
  >,
  'adminLogin' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAudioFile' : ActorMethod<[string], undefined>,
  'getAllAudioFiles' : ActorMethod<[], Array<AudioFile>>,
  'getAudioFile' : ActorMethod<[string], AudioFile>,
  'getAudioFilesByContext' : ActorMethod<[SoundContext], Array<AudioFile>>,
  'getAudioFilesByWorld' : ActorMethod<[Theme], Array<AudioFile>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];