/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface AudioFile {
    id: string;
    context: SoundContext;
    blob: ExternalBlob;
    description: string;
    world?: Theme;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum SoundContext {
    bossDefeat = "bossDefeat",
    worldUnlock = "worldUnlock",
    bomb = "bomb",
    clock = "clock",
    rewardClaim = "rewardClaim",
    bossObjective = "bossObjective",
    bossVictory = "bossVictory",
    layerOpen = "layerOpen",
    bossLevelStart = "bossLevelStart",
    tileMatch = "tileMatch",
    buttonClick = "buttonClick",
    backgroundMusic = "backgroundMusic",
    tileClear = "tileClear",
    tileClick = "tileClick",
    starEarned = "starEarned",
    shuffle = "shuffle",
    magnifier = "magnifier",
    levelComplete = "levelComplete"
}
export enum Theme {
    candyland = "candyland",
    ocean = "ocean",
    garden = "garden",
    space = "space",
    volcano = "volcano",
    forest = "forest"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAudioFile(id: string, context: SoundContext, world: Theme | null, blob: ExternalBlob, description: string): Promise<void>;
    adminLogin(password: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteAudioFile(id: string): Promise<void>;
    getAllAudioFiles(): Promise<Array<AudioFile>>;
    getAudioFile(id: string): Promise<AudioFile>;
    getAudioFilesByContext(context: SoundContext): Promise<Array<AudioFile>>;
    getAudioFilesByWorld(world: Theme): Promise<Array<AudioFile>>;
    getCallerUserRole(): Promise<UserRole>;
    isCallerAdmin(): Promise<boolean>;
}
import type { AudioFile as _AudioFile, ExternalBlob as _ExternalBlob, SoundContext as _SoundContext, Theme as _Theme, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAudioFile(arg0: string, arg1: SoundContext, arg2: Theme | null, arg3: ExternalBlob, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAudioFile(arg0, to_candid_SoundContext_n8(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAudioFile(arg0, to_candid_SoundContext_n8(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), await to_candid_ExternalBlob_n13(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async adminLogin(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAudioFile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAudioFile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAudioFile(arg0);
            return result;
        }
    }
    async getAllAudioFiles(): Promise<Array<AudioFile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAudioFiles();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAudioFiles();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAudioFile(arg0: string): Promise<AudioFile> {
        if (this.processError) {
            try {
                const result = await this.actor.getAudioFile(arg0);
                return from_candid_AudioFile_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAudioFile(arg0);
            return from_candid_AudioFile_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAudioFilesByContext(arg0: SoundContext): Promise<Array<AudioFile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAudioFilesByContext(to_candid_SoundContext_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAudioFilesByContext(to_candid_SoundContext_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAudioFilesByWorld(arg0: Theme): Promise<Array<AudioFile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAudioFilesByWorld(to_candid_Theme_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAudioFilesByWorld(to_candid_Theme_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
}
async function from_candid_AudioFile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AudioFile): Promise<AudioFile> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_SoundContext_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SoundContext): SoundContext {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Theme_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Theme): Theme {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Theme]): Theme | null {
    return value.length === 0 ? null : from_candid_Theme_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    context: _SoundContext;
    blob: _ExternalBlob;
    description: string;
    world: [] | [_Theme];
}): Promise<{
    id: string;
    context: SoundContext;
    blob: ExternalBlob;
    description: string;
    world?: Theme;
}> {
    return {
        id: value.id,
        context: from_candid_SoundContext_n19(_uploadFile, _downloadFile, value.context),
        blob: await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value.blob),
        description: value.description,
        world: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.world))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bossDefeat: null;
} | {
    worldUnlock: null;
} | {
    bomb: null;
} | {
    clock: null;
} | {
    rewardClaim: null;
} | {
    bossObjective: null;
} | {
    bossVictory: null;
} | {
    layerOpen: null;
} | {
    bossLevelStart: null;
} | {
    tileMatch: null;
} | {
    buttonClick: null;
} | {
    backgroundMusic: null;
} | {
    tileClear: null;
} | {
    tileClick: null;
} | {
    starEarned: null;
} | {
    shuffle: null;
} | {
    magnifier: null;
} | {
    levelComplete: null;
}): SoundContext {
    return "bossDefeat" in value ? SoundContext.bossDefeat : "worldUnlock" in value ? SoundContext.worldUnlock : "bomb" in value ? SoundContext.bomb : "clock" in value ? SoundContext.clock : "rewardClaim" in value ? SoundContext.rewardClaim : "bossObjective" in value ? SoundContext.bossObjective : "bossVictory" in value ? SoundContext.bossVictory : "layerOpen" in value ? SoundContext.layerOpen : "bossLevelStart" in value ? SoundContext.bossLevelStart : "tileMatch" in value ? SoundContext.tileMatch : "buttonClick" in value ? SoundContext.buttonClick : "backgroundMusic" in value ? SoundContext.backgroundMusic : "tileClear" in value ? SoundContext.tileClear : "tileClick" in value ? SoundContext.tileClick : "starEarned" in value ? SoundContext.starEarned : "shuffle" in value ? SoundContext.shuffle : "magnifier" in value ? SoundContext.magnifier : "levelComplete" in value ? SoundContext.levelComplete : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    candyland: null;
} | {
    ocean: null;
} | {
    garden: null;
} | {
    space: null;
} | {
    volcano: null;
} | {
    forest: null;
}): Theme {
    return "candyland" in value ? Theme.candyland : "ocean" in value ? Theme.ocean : "garden" in value ? Theme.garden : "space" in value ? Theme.space : "volcano" in value ? Theme.volcano : "forest" in value ? Theme.forest : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AudioFile>): Promise<Array<AudioFile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_AudioFile_n17(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_SoundContext_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SoundContext): _SoundContext {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Theme_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Theme): _Theme {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Theme | null): [] | [_Theme] {
    return value === null ? candid_none() : candid_some(to_candid_Theme_n11(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Theme): {
    candyland: null;
} | {
    ocean: null;
} | {
    garden: null;
} | {
    space: null;
} | {
    volcano: null;
} | {
    forest: null;
} {
    return value == Theme.candyland ? {
        candyland: null
    } : value == Theme.ocean ? {
        ocean: null
    } : value == Theme.garden ? {
        garden: null
    } : value == Theme.space ? {
        space: null
    } : value == Theme.volcano ? {
        volcano: null
    } : value == Theme.forest ? {
        forest: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SoundContext): {
    bossDefeat: null;
} | {
    worldUnlock: null;
} | {
    bomb: null;
} | {
    clock: null;
} | {
    rewardClaim: null;
} | {
    bossObjective: null;
} | {
    bossVictory: null;
} | {
    layerOpen: null;
} | {
    bossLevelStart: null;
} | {
    tileMatch: null;
} | {
    buttonClick: null;
} | {
    backgroundMusic: null;
} | {
    tileClear: null;
} | {
    tileClick: null;
} | {
    starEarned: null;
} | {
    shuffle: null;
} | {
    magnifier: null;
} | {
    levelComplete: null;
} {
    return value == SoundContext.bossDefeat ? {
        bossDefeat: null
    } : value == SoundContext.worldUnlock ? {
        worldUnlock: null
    } : value == SoundContext.bomb ? {
        bomb: null
    } : value == SoundContext.clock ? {
        clock: null
    } : value == SoundContext.rewardClaim ? {
        rewardClaim: null
    } : value == SoundContext.bossObjective ? {
        bossObjective: null
    } : value == SoundContext.bossVictory ? {
        bossVictory: null
    } : value == SoundContext.layerOpen ? {
        layerOpen: null
    } : value == SoundContext.bossLevelStart ? {
        bossLevelStart: null
    } : value == SoundContext.tileMatch ? {
        tileMatch: null
    } : value == SoundContext.buttonClick ? {
        buttonClick: null
    } : value == SoundContext.backgroundMusic ? {
        backgroundMusic: null
    } : value == SoundContext.tileClear ? {
        tileClear: null
    } : value == SoundContext.tileClick ? {
        tileClick: null
    } : value == SoundContext.starEarned ? {
        starEarned: null
    } : value == SoundContext.shuffle ? {
        shuffle: null
    } : value == SoundContext.magnifier ? {
        magnifier: null
    } : value == SoundContext.levelComplete ? {
        levelComplete: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
